InterviewText/Models/ErrorViewModel.cs
using System;

namespace InterviewText.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InterviewText/Models/GridInfoViewModel.cs
using System;

namespace InterviewText.Models
{
    public class GridInfoViewModel
    {
        public string Email { get; set; }

        public Guid TransactionNumber { get; set; }
    }
}

InterviewText/Models/PagedModel.cs
using System;

namespace InterviewText.Models
{
    public class PagedModel<T> where T : class
    {
        public Guid TransactionId { get; set; }

        public T Model { get; set; }

        public string Email { get; set; }
    }
}

InterviewText/Models/TransactionResultModel.cs
using System;

namespace InterviewText.Models
{
    public class TransactionResultModel
    {
        public string Email { get; set; }

        public Guid TransactionNumber { get; set; }

        public string Name { get; set; }
    }
}

InterviewText/Models/TransactionViewModel.cs
using System;

namespace InterviewText.Models
{
    public class TransactionViewModel
    {
        public Guid Id { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }
    }
}

InterviewText/Controllers/FileController.cs
using InterviewTest.Core.IService;
using InterviewTest.Core.Models;
using InterviewText.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using MimeMapping;

namespace InterviewText.Controllers
{
    public class FileController : Controller
    {
        private readonly IFileService _fileService;
        private readonly ITransactionService _transactionService;
        private readonly ITransactionComposerService _transactionComposerService;

        public FileController(IFileService fileService, 
            ITransactionService transactionService,
            ITransactionComposerService transactionComposerService)
        {
            _fileService = fileService;
            _transactionService = transactionService;
            _transactionComposerService = transactionComposerService;
        }

        [HttpPost]
        public async Task<IActionResult> UploadFiles(string email)
        {
            var fileDocument = Request.Form.Files;
            var files = new List<FileEntity>();

            foreach (var formFile in fileDocument)
            {
                if (formFile.Length > 0)
                {
                    var file = new FileEntity();

                    using (var stream = formFile.OpenReadStream())
                    {
                        file.FileData = ConvertStreamToByteArray(stream);
                    }

                    file.FileName = formFile.FileName;

                    files.Add(file);
                }
            }

            await _fileService.AddFileAsync(email, files);
            return Ok(true);
        }

        public IActionResult GridDocumentTransaction()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GridDocumentTransaction(GridInfoViewModel model)
        {
            await ValidateTransaction(model);

            var fileDetails = await _transactionComposerService.GetAllFileInfoByEmail(model.Email);

            var pagedModel = new PagedModel<IList<FileDetails>>
            {
                TransactionId = model.TransactionNumber,
                Model = fileDetails
            };

            return RedirectToAction("GridDocuments", pagedModel);
        }

        public IActionResult GridDocuments(PagedModel<IList<FileDetails>> pagedModelFileDetails)
        {
            return View(pagedModelFileDetails);
        }

        public async Task<IActionResult> Delete(Guid id, string email)
        {
            await _fileService.DeleteFileAsync(id);
            return RedirectToAction("GridDocumentTransaction", new GridInfoViewModel { TransactionNumber = id, Email = email });
        }

        public async Task<IActionResult> Download(Guid id)
        {
            var file = await _fileService.GetFileAsync(id);

            var outputStream = new MemoryStream(file.FileData);
            outputStream.Seek(0, SeekOrigin.Begin);

            return new FileStreamResult(outputStream, MimeUtility.GetMimeMapping(file.FileName));
        }

        private async Task ValidateTransaction(GridInfoViewModel model)
        {
            var transaction = await _transactionService.GetTransactionAsync(model.TransactionNumber);

            if (transaction.Email != model.Email)
            {
                ModelState.AddModelError("Error", "The transaction number or email is incorrect");
                throw new Exception("Invalid Model");
            };
        }

        private static byte[] ConvertStreamToByteArray(Stream input)
        {
            byte[] buffer = new byte[16 * 1024];
            using (MemoryStream memoryStream = new MemoryStream())
            {
                int read;
                while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
                {
                    memoryStream.Write(buffer, 0, read);
                }
                return memoryStream.ToArray();
            }
        }
    }
}

InterviewText/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using InterviewText.Models;

namespace InterviewText.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InterviewText/Controllers/TransactionController.cs
using AutoMapper;
using InterviewTest.Core.IService;
using InterviewTest.Core.Models;
using InterviewText.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace InterviewText.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly ITransactionComposerService _transactionComposerService;
        public TransactionController(ITransactionService transactionService,
            ITransactionComposerService transactionComposerService)
        {
            _transactionService = transactionService;
            _transactionComposerService = transactionComposerService;
        }

        public IActionResult AddTransaction()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddTransaction(TransactionViewModel model)
        {
            var transaction = Mapper.Map<TransactionEntity>(model);
            var transactionId = await _transactionComposerService.TransactEmailProcess(transaction);

            return RedirectToAction("TransactionDetails", new TransactionResultModel {
                TransactionNumber = transactionId,
                Email = model.Email,
                Name = model.FirstName + "" + model.LastName });
        }

        public IActionResult TransactionDetails(TransactionResultModel model)
        {
            return View(model);
        }
    }
}

InterviewText/Views/File/GridDocumentTransaction.cshtml
@model InterviewText.Models.GridInfoViewModel

@{
    ViewData["Title"] = "View";
}

<h4>Find Documents</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactionNumber" class="control-label"></label>
                <input asp-for="TransactionNumber" class="form-control" />
                <span asp-validation-for="TransactionNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InterviewText/Views/File/GridDocuments.cshtml
@model InterviewText.Models.PagedModel<IEnumerable<InterviewTest.Core.Models.FileDetails>>

@{
    ViewData["Title"] = "Grid Documents";
    var fileDetails = Model.Model;
}

<h4>Grid Documents</h4>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                File Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

@foreach (var item in fileDetails) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FileName)
            </td>
            <td>
                @Html.ActionLink("Download", "Download", "File", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", "File", new { id = Model.TransactionId, email = Model.Email })
            </td>
        </tr>
}
    </tbody>
</table>

InterviewText/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InterviewText/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InterviewText</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link href="~/lib/jquery-ui-1.12.1.custom/jquery-ui.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InterviewText</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - InterviewText - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/lib/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

InterviewText/Views/Transaction/AddTransaction.cshtml
@model InterviewText.Models.TransactionViewModel

@{
    ViewData["Title"] = "AddUser";
}

<h4>Add New User</h4>
<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="AddUser">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Id" type="hidden" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">First Name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Last Name</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" id="user-email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div id="file-browse" name="form" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-sm-6">
                        <input type="file" id="files" multiple />
                    </div>
                    <div class="col-sm-2">
                        <input type="button" id="upload-btn" class="btn btn-danger" value="Upload" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6" style="width:100px;">
                        <div id="progressbar" style="position:relative; display: none;">
                            <div class="progressbar-label" style="position: absolute;left: 48%;top: 20%;font-weight: bold;text-shadow: 1px 1px 0 #fff;">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/Script/file//app-file.js" asp-append-version="true"></script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InterviewText/Views/Transaction/TransactionDetails.cshtml
@model InterviewText.Models.TransactionResultModel

@{
    ViewData["Title"] = "TransactionDetails";
}

<h1>TransactionDetails</h1>

<div>
    <h4>Transaction Completed!</h4>
    <hr />
    <span>Hello @Model.Name</span>

    <span>Please save yout transaction nunmber for further viewing of files</span>

    <span>The email of {@Model.Email} generated a transaction number of {@Model.TransactionNumber}</span>
    <span>Thank you</span>
    <br />

    <span>Autogenerated</span>

</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>